<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Location;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // UBSs (Unidades Básicas de Saúde) de Guarapuava
        $locations = [
            [
                'name' => 'UBS Boqueirão',
                'short_name' => 'UBS-BOQ',
                'address' => 'Bairro Boqueirão',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.boqueirao@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Boqueirão',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Bonsucesso',
                'short_name' => 'UBS-BON',
                'address' => 'Bairro Bonsucesso',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.bonsucesso@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Bonsucesso',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Colibri',
                'short_name' => 'UBS-COL',
                'address' => 'Bairro Colibri',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.colibri@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Colibri',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Concórdia',
                'short_name' => 'UBS-CON',
                'address' => 'Bairro Concórdia',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.concordia@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde da Concórdia',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Entre Rios',
                'short_name' => 'UBS-ER',
                'address' => 'Bairro Entre Rios',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.entreiros@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Entre Rios',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Feroz',
                'short_name' => 'UBS-FER',
                'address' => 'Bairro Feroz',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.feroz@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Feroz',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Jardim Araucária',
                'short_name' => 'UBS-JA',
                'address' => 'Jardim Araucária',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.jardimaraucaria@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Jardim Araucária',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Jardim das Américas',
                'short_name' => 'UBS-JDA',
                'address' => 'Jardim das Américas',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.jardimamericanas@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Jardim das Américas',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Morro Alto',
                'short_name' => 'UBS-MA',
                'address' => 'Bairro Morro Alto',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.morroalto@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Morro Alto',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Paz e Bem',
                'short_name' => 'UBS-PB',
                'address' => 'Bairro Paz e Bem',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.pazebem@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Paz e Bem',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Parque das Árvores',
                'short_name' => 'UBS-PA',
                'address' => 'Parque das Árvores',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.parquearvores@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Parque das Árvores',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Planalto',
                'short_name' => 'UBS-PLA',
                'address' => 'Bairro Planalto',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.planalto@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Planalto',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Recanto Feliz',
                'short_name' => 'UBS-RF',
                'address' => 'Bairro Recanto Feliz',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.recantofeliz@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Recanto Feliz',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Residencial 2000',
                'short_name' => 'UBS-R2000',
                'address' => 'Residencial 2000',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.residencial2000@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Residencial 2000',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Santana',
                'short_name' => 'UBS-SAN',
                'address' => 'Bairro Santana',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.santana@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Santana',
                'is_active' => true,
            ],
            [
                'name' => 'UBS São Cristóvão',
                'short_name' => 'UBS-SC',
                'address' => 'Bairro São Cristóvão',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.saocristovao@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do São Cristóvão',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Santa Cruz',
                'short_name' => 'UBS-SCR',
                'address' => 'Bairro Santa Cruz',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.santacruz@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Santa Cruz',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Tancredo Neves',
                'short_name' => 'UBS-TN',
                'address' => 'Bairro Tancredo Neves',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.tancredoneves@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Tancredo Neves',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Vila Bela',
                'short_name' => 'UBS-VB',
                'address' => 'Vila Bela',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.vilabela@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde da Vila Bela',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Vila Carli',
                'short_name' => 'UBS-VC',
                'address' => 'Vila Carli',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.vilacarli@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde da Vila Carli',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Xarquinho I',
                'short_name' => 'UBS-X1',
                'address' => 'Bairro Xarquinho I',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.xarquinho1@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Xarquinho I',
                'is_active' => true,
            ],
            [
                'name' => 'UBS Xarquinho II',
                'short_name' => 'UBS-X2',
                'address' => 'Bairro Xarquinho II',
                'city' => 'Guarapuava',
                'state' => 'PR',
                'country' => 'Brasil',
                'postal_code' => null,
                'phone' => null,
                'email' => 'ubs.xarquinho2@guarapuava.pr.gov.br',
                'comment' => 'Unidade Básica de Saúde do Xarquinho II',
                'is_active' => true,
            ],
        ];

        foreach ($locations as $location) {
            Location::create($location);
        }
    }
}
