<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ramal;

class RamaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ramais = [
            ['departamento' => 'ALMOXARIFADO', 'descricao' => 'Atendimento', 'ramal' => '1610'],
            ['departamento' => 'CAPS', 'descricao' => 'CAPS AD - Enfermeira', 'ramal' => '1607'],
            ['departamento' => 'CAPS', 'descricao' => 'CAPS AD - Recepção', 'ramal' => '1606'],
            ['departamento' => 'CAPS', 'descricao' => 'CAPS II - Psicóloga', 'ramal' => '1604'],
            ['departamento' => 'CAPS', 'descricao' => 'CAPS II - Recepção', 'ramal' => '1603'],
            ['departamento' => 'CEO', 'descricao' => 'Administrativo', 'ramal' => '1600'],
            ['departamento' => 'CEO', 'descricao' => 'Almoxarifado', 'ramal' => '1601'],
            ['departamento' => 'CEO', 'descricao' => 'Coordenação', 'ramal' => '1599'],
            ['departamento' => 'CEO', 'descricao' => 'Recepção', 'ramal' => '1598'],
            ['departamento' => 'DACS', 'descricao' => 'Administrativo 1', 'ramal' => '1529'],
            ['departamento' => 'DACS', 'descricao' => 'Administrativo 2', 'ramal' => '1530'],
            ['departamento' => 'DACS', 'descricao' => 'Direção', 'ramal' => '1531'],
            ['departamento' => 'DAS', 'descricao' => 'Administrativo', 'ramal' => '1523'],
            ['departamento' => 'DAS', 'descricao' => 'Atenção Especializada', 'ramal' => '1525'],
            ['departamento' => 'DAS', 'descricao' => 'Atenção Primária', 'ramal' => '1526'],
            ['departamento' => 'DAS', 'descricao' => 'Direção', 'ramal' => '1524'],
            ['departamento' => 'DASMC', 'descricao' => 'Atendimento', 'ramal' => '1585'],
            ['departamento' => 'DASMC', 'descricao' => 'Centro de Saúde da Mulher - Enfermagem', 'ramal' => '1579'],
            ['departamento' => 'DASMC', 'descricao' => 'Centro de Saúde da Mulher - Monitoramento 1', 'ramal' => '1581'],
            ['departamento' => 'DASMC', 'descricao' => 'Centro de Saúde da Mulher - Monitoramento 2', 'ramal' => '1582'],
            ['departamento' => 'DASMC', 'descricao' => 'Centro de Saúde da Mulher - Monitoramento 3', 'ramal' => '1583'],
            ['departamento' => 'DASMC', 'descricao' => 'Centro de Saúde da Mulher - Monitoramento infantil', 'ramal' => '1584'],
            ['departamento' => 'DASMC', 'descricao' => 'Centro de Saúde da Mulher - Pré-consulta', 'ramal' => '1580'],
            ['departamento' => 'DASMC', 'descricao' => 'Centro de Saúde da Mulher - Recepção', 'ramal' => '1578'],
            ['departamento' => 'DASMC', 'descricao' => 'Direção', 'ramal' => '1577'],
            ['departamento' => 'DGTES', 'descricao' => 'Educação em Saúde', 'ramal' => '1505'],
            ['departamento' => 'DGTES', 'descricao' => 'Estágios', 'ramal' => '1508'],
            ['departamento' => 'DGTES', 'descricao' => 'Gestão de Pessoas', 'ramal' => '1507'],
            ['departamento' => 'DITIS', 'descricao' => 'Administrativo', 'ramal' => '1527'],
            ['departamento' => 'DITIS', 'descricao' => 'Direção', 'ramal' => '1528'],
            ['departamento' => 'DITIS', 'descricao' => 'Suporte', 'ramal' => '1512'],
            ['departamento' => 'DPGSUS', 'descricao' => 'Atendimento', 'ramal' => '1533'],
            ['departamento' => 'DRACA', 'descricao' => 'Agendamento de exames', 'ramal' => '1535'],
            ['departamento' => 'DRACA', 'descricao' => 'Auditoria', 'ramal' => '1566'],
            ['departamento' => 'DRACA', 'descricao' => 'Auditoria de Ecografia Obstétrica / Faturamento Hospitalar', 'ramal' => '1562'],
            ['departamento' => 'DRACA', 'descricao' => 'Cirurgias Eletivas', 'ramal' => '1561'],
            ['departamento' => 'DRACA', 'descricao' => 'Consultas e Especialidades', 'ramal' => '1565'],
            ['departamento' => 'DRACA', 'descricao' => 'Diretoria', 'ramal' => '1569'],
            ['departamento' => 'DRACA', 'descricao' => 'Faturamento Ambulatorial / Mamografias', 'ramal' => '1564'],
            ['departamento' => 'DRACA', 'descricao' => 'Fisioterapia', 'ramal' => '1563'],
            ['departamento' => 'DRACA', 'descricao' => 'Prontuário Médico', 'ramal' => '1556'],
            ['departamento' => 'DRACA', 'descricao' => 'Recepção', 'ramal' => '1560'],
            ['departamento' => 'DUE', 'descricao' => 'Departamento de Urgência e Emergência 1', 'ramal' => '1519'],
            ['departamento' => 'DUE', 'descricao' => 'Departamento de Urgência e Emergência 2', 'ramal' => '1521'],
            ['departamento' => 'FARMACIA MUNICIPAL', 'descricao' => 'Central de Abastecimento', 'ramal' => '1597'],
            ['departamento' => 'FARMACIA MUNICIPAL', 'descricao' => 'Dietas Especiais', 'ramal' => '1576'],
            ['departamento' => 'FARMACIA MUNICIPAL', 'descricao' => 'Recepção', 'ramal' => '1575'],
            ['departamento' => 'GABINETE', 'descricao' => 'Assessoria de Gabinete', 'ramal' => '1502'],
            ['departamento' => 'INFORMAÇÃO', 'descricao' => 'Assessoria de Informação', 'ramal' => '1509'],
            ['departamento' => 'JURÍDICO', 'descricao' => 'Assessoria Jurídica', 'ramal' => '1511'],
            ['departamento' => 'LABORATÓRIO MUNICIPAL', 'descricao' => 'Recepção', 'ramal' => '1570'],
            ['departamento' => 'LABORATÓRIO MUNICIPAL', 'descricao' => 'Setor Técnico / Exames', 'ramal' => '1571'],
            ['departamento' => 'MELHOR EM CASA', 'descricao' => 'Administrativo', 'ramal' => '1594'],
            ['departamento' => 'MELHOR EM CASA', 'descricao' => 'Atendimento', 'ramal' => '1596'],
            ['departamento' => 'MELHOR EM CASA', 'descricao' => 'Consultório A', 'ramal' => '1595'],
            ['departamento' => 'MELHOR EM CASA', 'descricao' => 'Enfermagem', 'ramal' => '1593'],
            ['departamento' => 'NÚCLEO SAÚDE DIGITAL', 'descricao' => 'Atendimento 0800', 'ramal' => '08006420019'],
            ['departamento' => 'NÚCLEO SAÚDE DIGITAL', 'descricao' => 'Atendimento Ramal', 'ramal' => '1700'],
            ['departamento' => 'OUVIDORIA', 'descricao' => 'Atendimento 1', 'ramal' => '1558'],
            ['departamento' => 'OUVIDORIA', 'descricao' => 'Atendimento 2', 'ramal' => '1559'],
            ['departamento' => 'PROTOCOLO', 'descricao' => 'Atendimento', 'ramal' => '1522'],
            ['departamento' => 'SAE', 'descricao' => 'AMPDS', 'ramal' => '1573'],
            ['departamento' => 'SAE', 'descricao' => 'Coordenação', 'ramal' => '1602'],
            ['departamento' => 'SAE', 'descricao' => 'Direção', 'ramal' => '1540'],
            ['departamento' => 'SAE', 'descricao' => 'Farmácia', 'ramal' => '1574'],
            ['departamento' => 'SAE', 'descricao' => 'Recepção', 'ramal' => '1572'],
            ['departamento' => 'SERVIÇO RESIDENCIAL TERAPÊUTICO', 'descricao' => 'Residência Terapêutica Feminina', 'ramal' => '1620'],
            ['departamento' => 'SERVIÇO RESIDENCIAL TERAPÊUTICO', 'descricao' => 'Residência Terapêutica Masculina', 'ramal' => '1621'],
            ['departamento' => 'TFD', 'descricao' => 'Transporte fora de Domicílio 1', 'ramal' => '1567'],
            ['departamento' => 'TFD', 'descricao' => 'Transporte fora de Domicílio 2', 'ramal' => '1568'],
            ['departamento' => 'TRANSPORTES', 'descricao' => 'Administrativo', 'ramal' => '1517'],
            ['departamento' => 'TRANSPORTES', 'descricao' => 'Manutenção de veículos', 'ramal' => '1515'],
            ['departamento' => 'TRANSPORTES', 'descricao' => 'Recepção', 'ramal' => '1516'],
            ['departamento' => 'TRANSPORTES', 'descricao' => 'Transportes', 'ramal' => '1514'],
            ['departamento' => 'TRANSPORTES', 'descricao' => 'Viagens e eventos', 'ramal' => '1518'],
            ['departamento' => 'UBS', 'descricao' => 'Adão Kaminski (ACS)', 'ramal' => '1619'],
            ['departamento' => 'UBS', 'descricao' => 'Adão Kaminski (Coordenação)', 'ramal' => '1618'],
            ['departamento' => 'UBS', 'descricao' => 'Adão Kaminski (Recepção)', 'ramal' => '1617'],
            ['departamento' => 'UBS', 'descricao' => 'Bonsucesso (ACS)', 'ramal' => '1645'],
            ['departamento' => 'UBS', 'descricao' => 'Bonsucesso (Enfermagem)', 'ramal' => '1646'],
            ['departamento' => 'UBS', 'descricao' => 'Bonsucesso (Recepção)', 'ramal' => '1644'],
            ['departamento' => 'UBS', 'descricao' => 'Boqueirão (ACS)', 'ramal' => '1672'],
            ['departamento' => 'UBS', 'descricao' => 'Boqueirão (Pré-consulta)', 'ramal' => '1671'],
            ['departamento' => 'UBS', 'descricao' => 'Boqueirão (Recepção)', 'ramal' => '1670'],
            ['departamento' => 'UBS', 'descricao' => 'Campo Velho (ACS)', 'ramal' => '1678'],
            ['departamento' => 'UBS', 'descricao' => 'Campo Velho (Recepção)', 'ramal' => '1677'],
            ['departamento' => 'UBS', 'descricao' => 'Campo Velho (Vacina)', 'ramal' => '1679'],
            ['departamento' => 'UBS', 'descricao' => 'Centro (ACS)', 'ramal' => '1698'],
            ['departamento' => 'UBS', 'descricao' => 'Centro (Coordenação)', 'ramal' => '1699'],
            ['departamento' => 'UBS', 'descricao' => 'Centro (Recepção)', 'ramal' => '1697'],
            ['departamento' => 'UBS', 'descricao' => 'Colibri (ACS)', 'ramal' => '1655'],
            ['departamento' => 'UBS', 'descricao' => 'Colibri (Recepção)', 'ramal' => '1654'],
            ['departamento' => 'UBS', 'descricao' => 'Concórdia (ACS)', 'ramal' => '1666'],
            ['departamento' => 'UBS', 'descricao' => 'Concórdia (Enfermagem)', 'ramal' => '1667'],
            ['departamento' => 'UBS', 'descricao' => 'Concórdia (Recepção)', 'ramal' => '1665'],
            ['departamento' => 'UBS', 'descricao' => 'Entre Rios (ACS)', 'ramal' => '1674'],
            ['departamento' => 'UBS', 'descricao' => 'Entre Rios (Recepção)', 'ramal' => '1673'],
            ['departamento' => 'UBS', 'descricao' => 'Entre Rios Volante', 'ramal' => '1690'],
            ['departamento' => 'UBS', 'descricao' => 'Feroz (ACS)', 'ramal' => '1616'],
            ['departamento' => 'UBS', 'descricao' => 'Feroz (Recepção)', 'ramal' => '1615'],
            ['departamento' => 'UBS', 'descricao' => 'Guairacá (Coordenação)', 'ramal' => '1703'],
            ['departamento' => 'UBS', 'descricao' => 'Guairacá (Recepção)', 'ramal' => '1688'],
            ['departamento' => 'UBS', 'descricao' => 'Guairacá (Sala da Vacina)', 'ramal' => '1689'],
            ['departamento' => 'UBS', 'descricao' => 'Guará (ACS)', 'ramal' => '1686'],
            ['departamento' => 'UBS', 'descricao' => 'Guará (Enfermagem)', 'ramal' => '1687'],
            ['departamento' => 'UBS', 'descricao' => 'Guará (Recepção)', 'ramal' => '1685'],
            ['departamento' => 'UBS', 'descricao' => 'Jardim Araucária (ACS)', 'ramal' => '1637'],
            ['departamento' => 'UBS', 'descricao' => 'Jardim Araucária (Recepção)', 'ramal' => '1636'],
            ['departamento' => 'UBS', 'descricao' => 'Jardim das Américas (ACS)', 'ramal' => '1653'],
            ['departamento' => 'UBS', 'descricao' => 'Jardim das Américas (Recepção)', 'ramal' => '1652'],
            ['departamento' => 'UBS', 'descricao' => 'Jordão (Recepção)', 'ramal' => '1680'],
            ['departamento' => 'UBS', 'descricao' => 'Jordão 1', 'ramal' => '1681'],
            ['departamento' => 'UBS', 'descricao' => 'Jordão 2', 'ramal' => '1682'],
            ['departamento' => 'UBS', 'descricao' => 'Morro Alto (ACS)', 'ramal' => '1639'],
            ['departamento' => 'UBS', 'descricao' => 'Morro Alto (Enfermagem)', 'ramal' => '1640'],
            ['departamento' => 'UBS', 'descricao' => 'Morro Alto (Recepção)', 'ramal' => '1638'],
            ['departamento' => 'UBS', 'descricao' => 'Palmeirinha (ACS)', 'ramal' => '1684'],
            ['departamento' => 'UBS', 'descricao' => 'Palmeirinha (Recepção)', 'ramal' => '1683'],
            ['departamento' => 'UBS', 'descricao' => 'Parque das Árvores (ACS)', 'ramal' => '1635'],
            ['departamento' => 'UBS', 'descricao' => 'Parque das Árvores (Recepção)', 'ramal' => '1634'],
            ['departamento' => 'UBS', 'descricao' => 'Paz e Bem (ACS)', 'ramal' => '1651'],
            ['departamento' => 'UBS', 'descricao' => 'Paz e Bem (Recepção)', 'ramal' => '1650'],
            ['departamento' => 'UBS', 'descricao' => 'Planalto (ACS)', 'ramal' => '1657'],
            ['departamento' => 'UBS', 'descricao' => 'Planalto (Coordenação)', 'ramal' => '1658'],
            ['departamento' => 'UBS', 'descricao' => 'Planalto (Recepção)', 'ramal' => '1656'],
            ['departamento' => 'UBS', 'descricao' => 'Primavera (Enfermagem)', 'ramal' => '1614'],
            ['departamento' => 'UBS', 'descricao' => 'Primavera (Recepção)', 'ramal' => '1613'],
            ['departamento' => 'UBS', 'descricao' => 'Recanto Feliz (ACS)', 'ramal' => '1623'],
            ['departamento' => 'UBS', 'descricao' => 'Recanto Feliz (Recepção)', 'ramal' => '1622'],
            ['departamento' => 'UBS', 'descricao' => 'Residencial 2000 (ACS)', 'ramal' => '1625'],
            ['departamento' => 'UBS', 'descricao' => 'Residencial 2000 (Recepção)', 'ramal' => '1624'],
            ['departamento' => 'UBS', 'descricao' => 'Rio das Pedras (Enfermagem)', 'ramal' => '1676'],
            ['departamento' => 'UBS', 'descricao' => 'Rio das Pedras (Recepção)', 'ramal' => '1675'],
            ['departamento' => 'UBS', 'descricao' => 'Santa Cruz (ACS)', 'ramal' => '1663'],
            ['departamento' => 'UBS', 'descricao' => 'Santa Cruz (Enfermagem - Coordenação)', 'ramal' => '1664'],
            ['departamento' => 'UBS', 'descricao' => 'Santa Cruz (Recepção)', 'ramal' => '1662'],
            ['departamento' => 'UBS', 'descricao' => 'Santana (ACS)', 'ramal' => '1642'],
            ['departamento' => 'UBS', 'descricao' => 'Santana (Coordenação)', 'ramal' => '1643'],
            ['departamento' => 'UBS', 'descricao' => 'Santana (Recepção)', 'ramal' => '1641'],
            ['departamento' => 'UBS', 'descricao' => 'São Cristóvão (ACS)', 'ramal' => '1633'],
            ['departamento' => 'UBS', 'descricao' => 'São Cristóvão (Recepção)', 'ramal' => '1632'],
            ['departamento' => 'UBS', 'descricao' => 'São Miguel (ACS)', 'ramal' => '1695'],
            ['departamento' => 'UBS', 'descricao' => 'São Miguel (Recepção)', 'ramal' => '1694'],
            ['departamento' => 'UBS', 'descricao' => 'Tancredo (ACS)', 'ramal' => '1669'],
            ['departamento' => 'UBS', 'descricao' => 'Tancredo (Recepção)', 'ramal' => '1668'],
            ['departamento' => 'UBS', 'descricao' => 'Vila Bela (ACS)', 'ramal' => '1660'],
            ['departamento' => 'UBS', 'descricao' => 'Vila Bela (Recepção)', 'ramal' => '1659'],
            ['departamento' => 'UBS', 'descricao' => 'Vila Carli (ACS)', 'ramal' => '1648'],
            ['departamento' => 'UBS', 'descricao' => 'Vila Carli (Coordenação)', 'ramal' => '1649'],
            ['departamento' => 'UBS', 'descricao' => 'Vila Carli (Recepção)', 'ramal' => '1647'],
            ['departamento' => 'UBS', 'descricao' => 'Xarquinho I (Recepção)', 'ramal' => '1626'],
            ['departamento' => 'UBS', 'descricao' => 'Xarquinho I (Sala ACS)', 'ramal' => '1627'],
            ['departamento' => 'UBS', 'descricao' => 'Xarquinho II (Fisioterapia)', 'ramal' => '1631'],
            ['departamento' => 'UBS', 'descricao' => 'Xarquinho II (Recepção)', 'ramal' => '1629'],
            ['departamento' => 'UBS', 'descricao' => 'Xarquinho II (Sala ACS)', 'ramal' => '1630'],
            ['departamento' => 'UPA', 'descricao' => 'Batel - Coordenação', 'ramal' => '1586'],
            ['departamento' => 'UPA', 'descricao' => 'Batel - Observação', 'ramal' => '1587'],
            ['departamento' => 'UPA', 'descricao' => 'Batel - Recepção', 'ramal' => '1588'],
            ['departamento' => 'URGÊNCIA', 'descricao' => 'Trianon - Eletro', 'ramal' => '1576'],
            ['departamento' => 'URGÊNCIA', 'descricao' => 'Trianon - Raio-X', 'ramal' => '1590'],
            ['departamento' => 'URGÊNCIA', 'descricao' => 'Ambulância', 'ramal' => '1532'],
            ['departamento' => 'URGÊNCIA', 'descricao' => 'Observação', 'ramal' => '1591'],
            ['departamento' => 'URGÊNCIA', 'descricao' => 'Primavera - Posto de Enfermagem', 'ramal' => '1612'],
            ['departamento' => 'URGÊNCIA', 'descricao' => 'Primavera - Recepção', 'ramal' => '1611'],
            ['departamento' => 'URGÊNCIA', 'descricao' => 'Trianon - Recepção', 'ramal' => '1589'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Administrativo Epidemio', 'ramal' => '1545'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Administrativo Vigilância Sanitária', 'ramal' => '1551'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'DANT', 'ramal' => '1537'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Direção Vigilância em Saúde', 'ramal' => '1547'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Direção Vigilância Epidemiológica', 'ramal' => '1543'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Direção Vigilância Sanitária', 'ramal' => '1546'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Fiscalização 1', 'ramal' => '1549'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Fiscalização 2', 'ramal' => '1550'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Fiscalização Sanitária', 'ramal' => '1538'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Ouvidoria', 'ramal' => '1557'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Centro Municipal de Imunização', 'ramal' => '1692'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Recepção', 'ramal' => '1555'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Sala Fiscais', 'ramal' => '1539'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Saúde Do Trabalhador 1', 'ramal' => '1548'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Saúde Do Trabalhador 2', 'ramal' => '1554'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'SIM | SINASC', 'ramal' => '1542'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'SINAN', 'ramal' => '1541'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Vacinas', 'ramal' => '1544'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Vigilância Ambiental 1', 'ramal' => '1552'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Vigilância Ambiental 2', 'ramal' => '1553'],
            ['departamento' => 'VIGILÂNCIA EPIDEMOLÓGICA E SANITÁRIA', 'descricao' => 'Vigilância Epidemiológica', 'ramal' => '1536'],
        ];

        foreach ($ramais as $ramal) {
            Ramal::create($ramal);
        }

        $this->command->info('Ramais importados com sucesso!');
    }
}
